name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:

jobs:
  deploy:
    name:  ${{ github.ref == 'refs/heads/master' && 'Production' || 'Staging' }} - Build & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      SWA_TOKEN: ${{ github.ref == 'refs/heads/master' && secrets.AZURE_SWA_DEPLOY_TOKEN_PROD || secrets.AZURE_SWA_DEPLOY_TOKEN_STAGING }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
          SO_USER_ID: '66384'
          NEXT_PUBLIC_SITE_URL: ${{ github.ref == 'refs/heads/master' && 'https://www.siddharthabbineni.in' || 'https://staging.siddharthabbineni.in' }}

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
          action: upload
          app_location: /
          output_location: .next
          skip_app_build: true
